### ISSUE TITLE
 added  jQuery Event handler - commit name

### ISSUE THREAD

**Issue by vickyantre** [Artinov/home-work-10-vickyantre#3]
I have to add one more ")" in 32 and 47 row in js file and i can`t understand why. Because I chanted just first row in every event. And before changes number of ")" this symbol (how to name it?) was enough.

**Comment by eko24ive** [comment]
Ok @vickyantre I'll look into this

**Comment by eko24ive** [comment]
You may refer to `(` as a round brace.
Let's talk about why you had to add this curly brace and compare jQuery event handler usage with regular JavaScript.

### Plain JavaScript
In native/vanilla/plain (regular JavaScript) we declare event handler as assignment of function to property, to be more specific - property of HTML Element we work with:
```js
htmlElement.onlick = function () {...}
```
This method will be executed when our event will "shoot", in this case - when we click on our element, we don't care about mechanism of this - browser does its job for us.

### jQuery
Lets recall that jQuery primary goal is to help our code work across all browsers. This achieved by many different ways, also `.onclick = ...` - is not the only way we can define event handler. So jQuery must ensure our code works ok and jQuery had to give us (developers) easy way to work with jQuery itself. So since we're working with function (event handler) - jQuery "takes" our function which we described and does its magic with it. You can see its pretty similar as `.forEach()` usage which also takes function.

So jQuery don't work like vanilla js - we don't use assignment statement here - we pass our function as argument for jQuery `.click()` method. You already know you can do it like this:
```js
$(htmlElement).click(function() {
  // our code
});
```

And this is why we have curly brace and round brace at the end `})`.
You can do it other way - define a function as variable and pass name of the variable:
```js
var eventHandler = function() {
  // our code
}

$(htmlElement).click(eventHandler)
```

Which works just the way you've seen it before.
It is common practice to define function as named variables in one file and "connect" them as event handlers in another. This results as some kind of simplicity and transparancy for code.
Hope I helped you with this one

**Comment by vickyantre** [comment]
I understood. Thank you.
